wildfly:
 rules:
   - id: id-1 
     title: "test124"
     notify: [Ankit-Bathwal,Aman,Ravi]
   - id: id-2
     body: "test567"
     notify: [Ankit-Bathwal,Cage]
 format:
   title:
     message: "Wrong content of the PR title"
   description:
     regexes:
       - pattern: "JIRA:\\s+https://issues.redhat.com/browse/WFLY-\\d+|https://issues.redhat.com/browse/WFLY-\\d+"
         message: "The PR description must contain a link to the JIRA issue"
 emails:
   - bathwal.ankit@gmail.com
   - baman@gyc.gys
